Add クリア画面まで3問分の問題
kanakanho/2024ProjectExercises1TeamC pull request #10
Opened 2024-05-21 10:07 UTC by kanakanho

## やったこと
- 問題3,4とクリア画面の実装
- ローカルストレージによる連携
- 今どの問題を解いているのかを分かりやすく

## やっていないこと
なし

## 画面のスクショ
<img width="1680" alt="image" src="https://github.com/kanakanho/2024ProjectExercises1TeamC/assets/76000830/307dc9aa-7c78-42bb-84d5-0e4ea764df73">

<img width="1680" alt="image" src="https://github.com/kanakanho/2024ProjectExercises1TeamC/assets/76000830/6aad2645-efad-413a-8c91-50ab9dae7c89">

<img width="1680" alt="image" src="https://github.com/kanakanho/2024ProjectExercises1TeamC/assets/76000830/0a53ebdc-27e0-44b7-9c52-a1358541ca98">

2024-05-23 02:50 UTC, ayuayuyu requested changes
変更をお願いします

2024-05-23 02:50 UTC, ayuayuyu commented on quiz/quiz2.html
> +            for (var i = 0; i < circles.length; i++) {
```
 var element = document.getElementById(idName);
 var circles = element.getElementsByTagName("circle");
```
は、下でも使っているためconstでどこかに宣言する方が良いと思います。
また、varである意味がわかりませんでした。

2024-05-23 02:50 UTC, ayuayuyu commented on quiz/quiz3.html
> +            var element = document.getElementById(idName);
同様

2024-05-23 02:50 UTC, ayuayuyu commented on quiz/quiz4.html
> +            let circles = document.querySelectorAll(".circleBox svg:not(.buttonCircle) circle");
letでなく、constにした方が良いと思います
他で使うのであれば関数ないではなく別で宣言をした方が良いと思います

2024-05-23 02:50 UTC, ayuayuyu commented on quiz/quiz4.html
> +            var element = document.getElementById(idName);
同様

2024-05-23 03:56 UTC, ayuayuyu requested changes
変更をお願いします

2024-05-23 03:56 UTC, ayuayuyu commented on quiz/clear.html
> +            document.querySelector(".circleBox").classList.add("popOutAnimation");
```suggestion
            document.querySelector(".circleBox").classList.add("popOutAnimation");
```
を```.getElementsByClassName("circleBox")[0].classList```にした方が良いと思います

2024-05-23 03:56 UTC, ayuayuyu commented on quiz/quiz2.html
> +            document.querySelector(".circleBox").classList.add("popOutAnimation");
同様

2024-05-23 03:56 UTC, ayuayuyu commented on quiz/quiz3.html
> +            document.querySelector(".circleBox").classList.add("popOutAnimation");
同様

2024-05-23 03:58 UTC, kanakanho commented on quiz/clear.html
> +            document.querySelector(".circleBox").classList.add("popOutAnimation");
直した

2024-05-23 03:59 UTC, kanakanho commented on quiz/quiz2.html
> +            for (var i = 0; i < circles.length; i++) {
直した

2024-05-23 03:59 UTC, kanakanho commented on quiz/quiz2.html
> +            document.querySelector(".circleBox").classList.add("popOutAnimation");
直した

2024-05-23 03:59 UTC, kanakanho commented on quiz/quiz3.html
> +            var element = document.getElementById(idName);
直した

2024-05-23 03:59 UTC, kanakanho commented on quiz/quiz3.html
> +            document.querySelector(".circleBox").classList.add("popOutAnimation");
直した

2024-05-23 04:00 UTC, kanakanho commented on quiz/quiz4.html
> +            let circles = document.querySelectorAll(".circleBox svg:not(.buttonCircle) circle");
直した

2024-05-23 04:00 UTC, kanakanho commented on quiz/quiz4.html
> +            var element = document.getElementById(idName);
直した

2024-05-23 04:03 UTC, ayuayuyu requested changes
変更をおねがします

2024-05-23 04:03 UTC, ayuayuyu commented on quiz/quiz2.html
> +            var element = document.getElementById(idName);
constに変更をお願いします

2024-05-24 03:54 UTC, kanakanho commented on quiz/quiz2.html
> +            var element = document.getElementById(idName);
直した

2024-05-27 03:36 UTC, ayuayuyu approved these changes

2024-05-27 03:36 UTC, ayuayuyu approved these changes
LGTM

2024-05-27 03:36 UTC, merged